### ISSUE TITLE
iOS doesn’t play when app is in the background

### ISSUE THREAD

**Issue by danias** [johnsonsu/react-native-sound-player#12]
While it works on Android and on the iOS emulator, on an actual iPhone, audio won’t play when the app is in the background.

**Comment by johnsonsu** [comment]
Hi @danias, thank you for using the package! I will consider adding background playing ability in the future, but for now, this library will stay simple. For the mean while, you may consider using a slightly more robust package https://github.com/react-native-kit/react-native-track-player.

**Comment by ithustle** [comment]
Hi @danias, try use with this lib https://github.com/tanguyantoine/react-native-music-control

**Comment by strawberry-code** [comment]
Any news here? Is now this library capable of playing sounds in background?

**Comment by ithustle** [comment]
@strawberry-code, I strongly recomend to use this one https://github.com/react-native-kit/react-native-track-player

**Comment by edferreira** [comment]
I've faced this issue too. I could solve It by using `SoundPlayer.setSpeaker(false)`.

To be able for an audio to be played in background the following category is needed to be setup. Which is done when you setSpeaker to false
`[session setCategory: AVAudioSessionCategoryPlayback error: nil]` 
Also you need to enable the Background Mode on your capabilities to enable audio, airplay and picture in picture

**Comment by jenipharachel** [comment]
@edferreira  Can you share more on what all you did to make this library play in the background state of a react-native app?

**Comment by jameszhong2008** [comment]
@jenipharachel 
Just call SoundPlayer.setSpeaker(false) before play sound in iOS.
