### ISSUE TITLE
[Question] I have a question!!

### ISSUE THREAD

**Issue by Yeonbin** [johnsonsu/react-native-sound-player#156]
**Describe the bug**
Actually this is not about bug, it just about question.
I'm making audio player using this library. 
So I made some function like play, pause, backward 10 seconds before, forward 10 seconds.
And I made progress bar using 'react-native-community/slider'.
My progress bar represent current position, and backward, forward position. But it can't show progressing status.
The point of progress bar just stop without moving. 

I think it can be possible but I don't know how to do..
Please let me know how should I do... 

**Expected behavior**
I want to get currentTime in realtime to make progress bar.

**Platform (please complete the following information):**
 - OS: ios, aos
 - react-native : 0.68.4

**Comment by johnsonsu** [comment]
Hi, I have not tried implementing a progress bar with the library before, but something involving a `setTimeout` or `setInterval` with `getInfo() => Promise<{currentTime: number, duration: number}>` should work.

Here is a music player UI example of a different sound player library for your reference:
https://github.com/benevbright/react-native-sound-playerview/blob/e04bfb53e0721e316bab68f1363bad65c6d83fa8/index.js#L31

**Comment by Yeonbin** [comment]
Thank you!
I made the function using setTimeout, setInterval with getInfo() function!! thank you for your replying!!
