### ISSUE TITLE
AAPT2: invalid package name

### ISSUE THREAD

**Issue by annacs94** [johnsonsu/react-native-sound-player#18]
I am getting this error for the `verifyReleaseResources` Gradle task after upgrading to
- react-native 0.57.1
- Android build tools 27.0.3
- Gradle 4.4

>  AAPT: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'rnsoundplayer'.

**Comment by johnsonsu** [comment]
Hi @annacs94, I have changed the package name and  published version 0.5.1. Can you please upgrade and let me know if it works for you? Thanks!

**Comment by annacs94** [comment]
It works, thank you for the quick fix!
