### ISSUE TITLE
Not working on react-native version "0.44.0"

### ISSUE THREAD

**Issue by kenziy** [johnsonsu/react-native-sound-player#2]
Hello guys I try to follow the instruction above but it seems that it is not working. it showing me this error

`undefined is not an object(eveluating 'RNSoundPlayer.playSoundFile')`
Im running it on android
using react-native version: `"version": "0.44.0"`

**Comment by johnsonsu** [comment]
Thank you for reporting the bug. It should be fixed now in version 0.2.1, please upgrade it using npm or yarn.

Don't forget to run `react-native link` after the `npm install` or `yarn`. I forgot to add that to the README in the previous version.

**Comment by unlimitedsux** [comment]
Hi please help, im facing the same issue. I have installed and ran everything needed in the documentation
