### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by tushgup** [johnsonsu/react-native-sound-player#22]
Hey! Thanks for developing this module, will be using it in an upcoming project.

This is probably a silly error but I've tried following the installation steps but I'm stuck at importing this package.

I opened it on Android Studio to check if it had been imported correctly, and that seems to be an issue. 
It's red at the import statement, and I don't see the corresponding folder on the left side section in the project structure. 

I followed the steps of installing using NPM & running react-native link.

Here are some screenshots:
![image](https://user-images.githubusercontent.com/5716459/47439504-1e81f880-d7ca-11e8-98be-27765fe77510.png)
![image](https://user-images.githubusercontent.com/5716459/47439539-293c8d80-d7ca-11e8-8471-d2bde35d7dba.png)

This is the error I get when I run `react-native run-android`
![image](https://user-images.githubusercontent.com/5716459/47439738-88020700-d7ca-11e8-9c72-eb1a30f941cf.png)

**Comment by tushgup** [comment]
Okay so @johnsonsu, I figured out how to fix it... I had to change the import name to `rnsoundplayer.RNSoundPlayerPackage` instead of `com.johnsonsu.rnsoundplayer.RNSoundPlayerPackage`! 

Not sure why though, seems like you recently committed to change to a new package name? Anyway, hopefully there's a way to fix this automatically for other people who want to use this package! :)

**Comment by johnsonsu** [comment]
Thank your for sending the bug report! I did change the package name recently and I forgot to publish the new version with the directory changes, sorry about the trouble!

**Comment by flogy** [comment]
Hello,

First of all thank you for this nice and lightweight library! It fits perfectly to my current project as it does not do too much or too little and also works well.

However, I still have this issue with version 0.5.2. The Java classes seem to be in the correct package directory now as specified in the AndroidManifest.xml, but the package definition inside the two classes is still wrong. I quickly created a pull request containing the changes which worked for me.

Cheers and keep up the great work!
