### ISSUE TITLE
SoundPlayer.onFinishedPlaying is not a function

### ISSUE THREAD

**Issue by ithustle** [johnsonsu/react-native-sound-player#24]

**Comment by johnsonsu** [comment]
Seems like it's working for me. What platform are you on and what version of the package are you using?

**Comment by ithustle** [comment]
I'm using windows 10 and latest version of package

**Comment by johnsonsu** [comment]
@ithustle Hmm, that's strange. Can you try a different audio file to make sure it's not the the file's problem?

**Comment by ithustle** [comment]
@johnsonsu I also try a different audio and no lucky ... Maybe was because you didn't set this => `mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);`

**Comment by ithustle** [comment]
@johnsonsu the problem is in my project. I don't know how and why but I figure it out and I'll try to solve it. Sorry for it and thanks for your time...

**Comment by johnsonsu** [comment]
@ithustle I'm glad you solve it, good work!
