### ISSUE TITLE
Feature Request: onStartedPlaying

### ISSUE THREAD

**Issue by flogy** [johnsonsu/react-native-sound-player#28]
Hi @johnsonsu 

I am currently working at a project where it is very important to synchronize a particular action with a sound effect. Now I discovered that there sometimes is a slight delay between the `playSoundFile` call and when I can actually hear the sound. I believe this might be because the system needs some time to load the sound first..?

However, a great solution for this would be to have a callback similar to `onFinishedPlaying` that is called as soon as the sound is loaded and actually started playing. Would it be possible to introduce a new `onStartedPlaying` callback for this purpose?

Cheers

**Comment by flogy** [comment]
I do no longer require this, but maybe it make sense to include it anyways? Or else, just close it. Thank you!

**Comment by johnsonsu** [comment]
@flogy Sorry for the late reply. Thank you for letting me know you got it working! I will keep this open for now and implement a solution as soon as possible.

**Comment by johnsonsu** [comment]
The solution to this problem is implemented with #30 and #32!
