### ISSUE TITLE
Proposal: keep awake while playing

### ISSUE THREAD

**Issue by assertchris** [johnsonsu/react-native-sound-player#31]
It would be neat if there was an option to keep the device's screen from switch off while playing music. Currently, I am using https://github.com/corbt/react-native-keep-awake to do this. Perhaps it's not the sort of thing you want this library to do (and I completely understand that). I'd suggest at least documenting that the screen will still go off, and suggesting what can be done to prevent that...

**Comment by johnsonsu** [comment]
Hi, thank you for the proposal!
I added a note about this issue and the link to the library in the doc for now. The implementation of the keep awake feature seems not that complicated. I will add the feature soon and will keep this issue open for now.
