### ISSUE TITLE
setVolume for soundPlayer

### ISSUE THREAD

**Issue by mlop113** [johnsonsu/react-native-sound-player#36]
How I can setVolume for soundPlayer while I playing an Song. example: "soundPlayer.setVolume(0.5)"

**Comment by mlop113** [comment]
same issue

**Comment by johnsonsu** [comment]
@mlop113 Hi, I just added this feature and published `0.6.2`, please give it a try, thank you!

**Comment by mlop113** [comment]
thank you very much

**Comment by chrismang** [comment]
Hi, is working excellent with Android, but I couldn't make it work with iOS. I try different numbers (0.1, 0.5) and the volume is always maximum. What can I do?

**Comment by gurol** [comment]
Yes, I have the same issue here in iOS. No change in sound level. It is always the maximum (version 0.6.2).

**Comment by johnsonsu** [comment]
Hi @chrismang, @gurol , how are you setting the volume? Can you try setting it inside the callback `onFinishedLoading`? You can try something like this:
```
  componentDidMount() {
    SoundPlayer.onFinishedLoading((success: boolean) => {
      console.log('finished loading', success)
      soundPlayer.setVolume(this.state.volume)
    })
  }
  
  setVolume(volume) {
    soundPlayer.setVolume(volume)
    this.setState({ volume })
  }

```
This is because on iOS the player might be deallocated in some cases.

**Comment by gurol** [comment]
Hi @johnsonsu, I simply change the volume before playing the local mp3 file:

```
SoundPlayer.setVolume(0.25);
SoundPlayer.playSoundFile('example, 'mp3');
```

**Comment by johnsonsu** [comment]
@gurol , can you try changing it after? Because the current implementation will only instantiate the player when playing the sound. I will change the implementation in the next update.
