### ISSUE TITLE
[iOS] Problem listening FinishedLoading

### ISSUE THREAD

**Issue by EzeRangel** [johnsonsu/react-native-sound-player#39]
It seems the index.js in the package has not registered the FinishedLoading for iOS. I got this warning `Sending "FinishedLoading" with no listeners registered.`

**Comment by johnsonsu** [comment]
Hi @EzeRangel ,I can't seem to reproduce this warning on my machine. Are you on version `0.6.1`?

**Comment by EzeRangel** [comment]
Yes, this is part of my code.

```
prepareSound = () => {
    SoundPlayer.loadSoundFile('order', 'mp3');
    SoundPlayer.onFinishedLoading((success) => {
      console.log(success);

      if (success) {
        this.canPlay = true;
      }
    });
  }
```

The `onFinishedLoading` method is unreachable. This only happens in iOS

**Comment by SteponasIvasovas** [comment]
same problem

**Comment by johnsonsu** [comment]
Hi guys, have you tried playing that file? Does it work? If it does, does it fire the event?

**Comment by gurol** [comment]
Simple `SoundPlayer.playSoundFile('example', 'mp3');`without loading in version 0.6.2 also triggers the same warnings in my case.

**Comment by johnsonsu** [comment]
You should mount the listener before the `loadSoundFile` is called, i.e.
```
prepareSound = () => {    SoundPlayer.onFinishedLoading((success) => {
      console.log(success);

      if (success) {
        this.canPlay = true;
      }
    });
    SoundPlayer.loadSoundFile('order', 'mp3');
  }
```
Also, it's better to only mount the listener once, so it's better to do:
```
  componentDidMount() {
    SoundPlayer.onFinishedLoading((success: boolean) => {
      console.log('finished loading', success)
    })
    // add other listeners here as needed
  }

```
