### ISSUE TITLE
downloading file when using ```plauUrl```

### ISSUE THREAD

**Issue by mlop113** [johnsonsu/react-native-sound-player#44]
If I use ```playUrl``` then I set SoundPlayer.pause(), so in this time for pausing, SoundPlayer is still continue downloading from my Url, is it?

**Comment by johnsonsu** [comment]
The `playUrl` function is implemented using [AVPlayer](https://developer.apple.com/documentation/avfoundation/avplayer) on iOS, and [MediaPlayer](https://developer.android.com/guide/topics/media/mediaplayer) on Android. I couldn't find any documentation on the behaviour of `pause()`. However, I think it is still downloading in during pause.

**Comment by mlop113** [comment]
thank your, you are the best
