### ISSUE TITLE
Issue: Can I play multiple songs at the same time? Using many different SoundPlayer?

### ISSUE THREAD

**Issue by mlop113** [johnsonsu/react-native-sound-player#48]

**Comment by mlop113** [comment]
just like this: 
```
import SoundPlayer from 'react-native-sound-player'
import SoundPlayer2 from 'react-native-sound-player'
import SoundPlayer3 from 'react-native-sound-player'

SoundPlayer.playSoundFile('All rise', 'wav')
SoundPlayer2.playSoundFile('Bang_bang_bang', 'wav')
SoundPlayer3.playSoundFile('love_story', 'wav')
```

**Comment by johnsonsu** [comment]
Hi @mlop113 No, this library cannot play multiple songs at the same time. The current implementation is similar to a singleton, when a new song is played, the previous instance of player will be either reused or destroyed.

To do what you wanted, we will need a completely new architecture for the library with new usage APIs. I will mark this as enhancement for now, but I cannot give you a date on when I'm able to implement it.

**Comment by mlop113** [comment]
thank you

**Comment by RWOverdijk** [comment]
@mlop113 https://github.com/zmxv/react-native-sound can do this. It has been around for a while now but it works well :)

**Comment by mlop113** [comment]
@RWOverdijk  it maybe good with iOS but when I use for android, it load song from url get more time.
