### ISSUE TITLE
Task :react-native-sound-player:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by moseslucas** [johnsonsu/react-native-sound-player#49]
Error generating signed apk.

React Native version `0.59.8`

Steps to reproduce.
1. I followed the instruction. 
 - `yarn add react-native-sound-player`
 - `react-native link react-native-sound-player`
 -  followed the basic sound playing

2. Generate signed apk. 
 - `cd android && ./gradlew assembleRelease`

Build fails and shows this message

<img width="837" alt="Screen Shot 2019-05-14 at 5 43 50 PM" src="https://user-images.githubusercontent.com/30344224/57688520-3a6ac000-7670-11e9-96c5-c766ebd9c79f.png">

**Comment by johnsonsu** [comment]
Hi @moseslucas, thank you for using the library and submitting the issue! I just published a new version `0.7.1`, please give it a try and hopefully this fixes your issue. You can upgrade by running:
```
yarn upgrade react-native-sound-player --latest
```
