### ISSUE TITLE
Build failed: ld: library not found for -lPlaySound in Xcode

### ISSUE THREAD

**Issue by yananym** [johnsonsu/react-native-sound-player#5]
Trying to build in Xcode - getting 
 library not found for -lPlaySound
error consistently. It does not seem to be present in the repo itself - am I missing anything?

**Comment by johnsonsu** [comment]
Hi, sorry for the late reply. Are you still having this issue?

**Comment by tomahawk291** [comment]
This error still happens to me. Any solution?

**Comment by johnsonsu** [comment]
@tomahawk291 Please try using the latest version on npm `0.5.3`
