### ISSUE TITLE
Android - cannot play locally downloaded file

### ISSUE THREAD

**Issue by shmoogems** [johnsonsu/react-native-sound-player#53]
Is there a way to play songs from somewhere other than the main bundle location (eg. external storage or a documents folder) ? 

It's a similar question to [#10](https://github.com/johnsonsu/react-native-sound-player/issues/10) - but wondering if there is an Android implementation for the fallback mentioned in the solution?

PS. Thank you to you and all contributors for this library, very handy!

**Comment by shmoogems** [comment]
The actual error I'm encountering is in `RNSoundPlayerModule.java` - where MediaPlayer.create is returning null and assigning it to this.mediaPlayer
`this.mediaPlayer = MediaPlayer.create(getCurrentActivity(), this.getUriFromFile(name, type));`

Then a null reference error happens during:
`this.mediaPlayer.setOnCompletionListener`

The mp3 file I'm trying to load is in the /data/data/com.package/files directory - can anyone tell me if this is where it's supposed to be?

**Comment by johnsonsu** [comment]
Hi @shmoogems, what parameters are you passing into the function? The library will look for the file inside the folder:
```java
    String folder = getReactApplicationContext().getFilesDir().getAbsolutePath();
```
Which should be the folder you are storing the file.

**Comment by shmoogems** [comment]
```
import SoundPlayerVoice from 'react-native-sound-player'
...
SoundPlayerVoice.loadSoundFile('track_name', 'mp3') 
```
My track name actually does have an underscore in it, could this be the problem?

**Comment by shmoogems** [comment]
It seems like the underscore in the track name IS the problem, removing the underscores from the names seems to fix the issue.

(even though I read somewhere that android's MediaPlayer accepts alphanumeric and underscore... )

Is this a general rule for your library too?

**Comment by johnsonsu** [comment]
Android file system should be fine with underscore, so I'm not sure what the actual problem is. However, I'm glad you fixed it!
