### ISSUE TITLE
playSound is not a function.

### ISSUE THREAD

**Issue by omkarsk98** [johnsonsu/react-native-sound-player#54]
@omkarsk98, you can use the `playSound('/pathToTheFileYouWantToPlay/filename', 'filetype')` function with the path to the file and its type. You need to get the path using `react-native-fs` or whatever you used to download the file.

I will lock this conversation, please create an issue if you have further questions.

_Originally posted by @johnsonsu in https://github.com/johnsonsu/react-native-sound-player/pull/37#issuecomment-495765870_

It returns playSound is not a function when using the above method. It does not show this function even in the module. Is there any alternative? Please help.

**Comment by johnsonsu** [comment]
It should be `playSoundFile`

**Comment by omkarsk98** [comment]
If it is so, please update your docs.
It still doesnt help with playSoundFile method.

**Comment by johnsonsu** [comment]
The doc has been updated already.

How are you storing the file in your system? Can you post some of your code here?

**Comment by omkarsk98** [comment]
I am reading the music files from the phone dynamically . I am using [react-native-get-music-files](https://www.npmjs.com/package/react-native-get-music-files). It returns an array of objects with all the music files and their paths. A sample return value is here.
`[
  {
    id : 1,
    title : "La danza del fuego",
    author : "Mago de Oz",
    album : "Finisterra",
    genre : "Folk",
    duration : 132132312321, // miliseconds
    cover : "file:///sdcard/0/123.png",
    blur : "file:///sdcard/0/123-blur.png", //Will come null if createBLur is set to false
    path : "/sdcard/0/la-danza-del-fuego.mp3"
  }
]`
So what do I use as the parameters for the function playSoundFile()?
Please help.

**Comment by johnsonsu** [comment]
Can you please try `playSoundFile("file:///sdcard/0/la-danza-del-fuego.mp3")`?
Basically try add `file://` in front of the `path` returned to you from `react-native-get-music-files`.
