### ISSUE TITLE
Important typo in FinishedPlyaing in README

### ISSUE THREAD

**Issue by LucaLovagnini** [johnsonsu/react-native-sound-player#55]
In README file, under `addEventListener` section there's an error:

`    _onFinishedPlayingSubscription = SoundPlayer.addEventListener('**FinishedPlyaing**', ({ success }) => {`

Instead of:

`    _onFinishedPlayingSubscription = SoundPlayer.addEventListener('**FinishedPlaying**', ({ success }) => {`

This caused a bug from my quick copy/paste =)

**Comment by johnsonsu** [comment]
Nice catch! Thanks!
