### ISSUE TITLE
SoundPlayer.onFinishedLoading(this.loadedSound) doesn't wait to load

### ISSUE THREAD

**Issue by unutoiul** [johnsonsu/react-native-sound-player#56]
```
SoundPlayer.onFinishedLoading(this.loadedSound);
loadedSound(data) {
        console.log(data); --> always true
    }
``` 
doesn't wait to load and is triggering the event straight away and is always loaded with success.

never received and error.

**Comment by johnsonsu** [comment]
Hi @unutoiul, yes this function will always return true. In fact, when `playSoundFile`, `playUrl` functions fail, they will throw an native error immediately and `onFinishedLoading` will not be called.
