### ISSUE TITLE
Playing online audio files

### ISSUE THREAD

**Issue by BlagojeV93** [johnsonsu/react-native-sound-player#6]
Are there plans for updates on playing online audio files from network? I really like this library, it's super easy to implement, and this feature would make it a lot better

**Comment by johnsonsu** [comment]
Hi, thank you for using the library and I'm glad you like it! That's a great suggestion, I will try to add steaming online audio feature if it doesn't complicate things too much. Cheers!

**Comment by johnsonsu** [comment]
Sorry about the long overdue update, version `0.4.0` is out and supports playing audio file from URL. Hope you guys like it and thank you for using the lib!
