### ISSUE TITLE
Background player controls not displaying

### ISSUE THREAD

**Issue by AnilkumarDO** [johnsonsu/react-native-sound-player#60]
Thanks for the good library. It is playing background well, But, It is not showing controls in background/lock screen mode in notification bar.

Is there anything do we need to enable, But, I did not found anything regarding this in documentation.
Please check following link for more details about this query.

(https://stackoverflow.com/questions/56826867/how-to-show-media-controls-in-lockscreen-background-state-in-react-native

)Can anyone help us?

**Comment by johnsonsu** [comment]
Hi @AnilkumarDO, this feature is not implemented in the library currently. There are ways to do it and it will require writing native code. You can look for resources on lock screen media control on each platform to get more information.

For Android, this link might be useful:
https://gist.github.com/ianhanniballake/15dce0b233b4f4b23ef8
