### ISSUE TITLE
How to keep move slider value according to audio play duration

### ISSUE THREAD

**Issue by AnilkumarDO** [johnsonsu/react-native-sound-player#64]
Thanks for the good library. We are using this, But, For the progress of the audio, We are showing Slider in UI. But, We have to keep move the progress bar status according to audio play.

Is there any method to get keep information about audio status?
And how to track buffering audio state? Is there any delegate method?
Also it is taking time to play URL like 5 to 10 seconds for online streaming, How to get is preparing play kind states?

**Comment by AnilkumarDO** [comment]
I found solution myself by updating current time for state.

**Comment by jaccotaco** [comment]
Can you share your code?

**Comment by jaccotaco** [comment]
@AnilkumarDO

**Comment by smubarak-ali** [comment]
@jaccotaco 
I have done something similar and pasting some code snippet below:

> const { duration, currentTime } = info;
> const elapsed = currentTime / duration;
> const percetageElapsed = elapsed * 100;
> this.setState({
>                     currentTime: currentTime,
>                     songDuration: duration,
>                     elapsedInPercent: Math.round(percetageElapsed),
>                 });

You can use the elapsedInPercent value to dynamically change the slider value or anything.

This whole function is wrapped around setInterval(() => ..., 2000), so it updates every 2 seconds. Also, don't forget to clearInterval on componentWillUnmount()
