### ISSUE TITLE
Can't play any track..

### ISSUE THREAD

**Issue by losheredos** [johnsonsu/react-native-sound-player#7]
My codes : 
import SoundPlayer from 'react-native-sound-player';

playTrack(){
        try {
            SoundPlayer.playSoundFile('free', 'mp3');
        } catch (e) {
            console.log(`cannot play the sound file`, e);
        }
    }

When I call this function I get error in console log; 

"cannot play the sound file TypeError: Cannot read property 'playSoundFile' of undefined"

What I should do ?.. I checked all options again and again, I linked correctly, mp3 files are located in raw.. I dont know what else I can do .

Edit: I run react-native run-android to compile the project again now its not giving error but I dont hear any sounds..

**Comment by losheredos** [comment]
OK guys I solved it so it was about my android simulator had no sound itself.. If you will have a similar problem like me you can check first your android simulator's sound.

**Comment by johnsonsu** [comment]
Glad you fix it! Thanks for the update and info. They will be helpful for others!
