### ISSUE TITLE
[BUG] Not able ro run app after adding this lib.

### ISSUE THREAD

**Issue by akashmi** [johnsonsu/react-native-sound-player#73]
**Getting error after adding this lib**

Error: Native module can not be null

![Screenshot 2019-09-18 at 6 53 03 PM](https://user-images.githubusercontent.com/11882168/65154481-36e5ac00-da49-11e9-9e3c-268c27f73f36.png)

**Comment by johnsonsu** [comment]
If you are using ReactNative 0.60.5, can you try downgrading to 0.60.4 and see if it works?

**Comment by rutgermaxnl** [comment]
Had the same issue on RN 0.60.5. After doing a "pod install" everything works fine for me.
