### ISSUE TITLE
Playing 2.track is not overlapping

### ISSUE THREAD

**Issue by losheredos** [johnsonsu/react-native-sound-player#9]
So in my app I use musics like a radio and, sometimes there is effects like 2-3 seconds. But when radio is open and when I try to play sound effect, its not overlapping?.. instead its closing first music .. what I can do about it?

**Comment by johnsonsu** [comment]
Hi @losheredos, unfortunately there is no way around it at this moment.

To keep this library simple, I implemented it in a way that only one audio player can exist at any given time. This helps with things like memory management and `onFinishedPlaying()` event handling.

To make it work with with multiple audio player, we need to assign some kind of ID to each instance of the player and each `play()`, `pause()`, etc will require an ID parameter, which is passed to the native thread.

I have no plans implementing these features at the moment, but you are welcome to fork the library and implement what you need. Cheers!

**Comment by losheredos** [comment]
Yeah thank you! I just used react-native sound package, and I use yours to implement effects. Your package and react-native sound work nice together, so I'm very fine about it :) . Thank you for answering and thanks for this library.

**Comment by johnsonsu** [comment]
Thank you for using the library and your support!
