### ISSUE TITLE
[BUG]TypeError: "can't access property "playUrl", RNSoundPlayer is undefined"

### ISSUE THREAD

**Issue by Vn-ChemGio** [johnsonsu/react-native-sound-player#93]
Hi guy!
I'm start using react-native-sound-player in my project;
I had been install package with NPM
---
then I import SoundPlayer from 'react-native-sound-player';
and insert 
try {
                // play the file tone.mp3
                //SoundPlayer.playSoundFile('tone', 'mp3')
                // or play from url
                SoundPlayer.playUrl(`${REMOTE_URL}${url}`)
            } catch (e) {
                console.log(`cannot play the sound file`, e)
            }
to MyComponnent as a document 
All correct with document, but I had error in Console of Browser:

> "can't access property "playUrl", RNSoundPlayer is undefined"

Can you tell me how to fix it

**Comment by Vn-ChemGio** [comment]
Note : Im using 
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",

**Comment by FaizanMostafa** [comment]
I am having the same issue, any luck yet?

**Comment by deeksha-zibal** [comment]
I am also facing the same issue in Android
![Screenshot_1611736621](https://user-images.githubusercontent.com/58543516/105965015-f53b2b80-60a8-11eb-8974-1fca30eb4b89.png)
, Is It fixed?

**Comment by AdamStone** [comment]
Try rebuilding the native app (`npx react-native run-android`). RNSoundPlayer is a custom native module, so if you don't do a new native build after `npm install react-native-sound-player` the JS will run but this module will be undefined.

**Comment by renatozr** [comment]
Maybe this can help: https://docs.expo.dev/versions/latest/sdk/audio/

**Comment by zennolux** [comment]
> Try rebuilding the native app (`npx react-native run-android`). RNSoundPlayer is a custom native module, so if you don't do a new native build after `npm install react-native-sound-player` the JS will run but this module will be undefined.

yeah, it works for me, great help, thanks a lot.
