### ISSUE TITLE
After stop how to play again from start its not playing again from start

### ISSUE THREAD

**Issue by nivas412** [johnsonsu/react-native-sound-player#98]
**Describe the bug**

In the middle of the song if I called SoundPlayer.stop(), I am unable to play from start again how can I achieve this ??

if i called SoundPlayer.playUrl(this.state.audioUrl); its not playing anything.

**To Reproduce**
1. SoundPlayer.loadUrl(audioCacheUrl); - called
2. play() - called
3. stop() - called
4. SoundPlayer.loadUrl(audioCacheUrl); - not working ,  play() - also not working if i go another component also not working

**Expected behavior**
whenever i called SoundPlayer.loadUrl(audioCacheUrl); it should play from start.

**Platform (please complete the following information):**
Android

**Additional context**
All infomation has given above.

**Comment by nivas412** [comment]
For solving this issue i used seek0 and pause() solves my issue

**Comment by KaviduAloka** [comment]
What worked for me is,

```
SoundPlayer.playUrl(url);
SoundPlayer.seek(time);
```
